trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_m_gpu
  workerType: complex_model_m_gpu
  workerCount: 3
  parameterServerType: complex_model_m_gpu
  parameterServerCount: 3
  runtimeVersion: "1.1" 
